#!/usr/bin/env node
/**
 * Seed script for Oxford 3000 words into Supabase.
 * 
 * Usage: node scripts/seed_oxford3000.ts
 * 
 * Environment variables required:
 *   SUPABASE_URL - Your Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY - Your Supabase service role key
 * 
 * Input: Place the full 3000-word JSON array at src/data/oxford3000_seed.json
 * (Generated by Cursor using the prompt provided in the README)
 */

import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const SEED_FILE = process.env.SEED_FILE ?? "src/data/oxford3000_seed.json";

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("❌ Error: Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables.");
  console.error("   export SUPABASE_URL=https://your-project.supabase.co");
  console.error("   export SUPABASE_SERVICE_ROLE_KEY=your_service_role_key");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

type OxfordWord = {
  word: string;
  translation: string;
  difficulty_level: "A1" | "A2" | "B1" | "B2";
  frequency_rank: number;
  phonetic: string;
  example_sentence: string;
};

async function main() {
  const seedPath = resolve(process.cwd(), SEED_FILE);

  let words: OxfordWord[];
  try {
    const raw = readFileSync(seedPath, "utf-8");
    words = JSON.parse(raw) as OxfordWord[];
  } catch (error) {
    console.error(`❌ Error: Could not read ${seedPath}`);
    console.error("   Generate the file first using the Cursor prompt.");
    process.exit(1);
  }

  if (!Array.isArray(words) || words.length === 0) {
    console.error("❌ Error: Seed file must contain a non-empty JSON array.");
    process.exit(1);
  }

  console.log(`📖 Loaded ${words.length} words from ${seedPath}`);

  // Deduplicate by lowercase word
  const seen = new Set<string>();
  const uniqueWords = words.filter((w) => {
    const key = w.word.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  console.log(`✅ ${uniqueWords.length} unique words (removed ${words.length - uniqueWords.length} duplicates)`);

  // Insert in batches
  const batchSize = 200;
  let inserted = 0;
  let updated = 0;

  for (let i = 0; i < uniqueWords.length; i += batchSize) {
    const batch = uniqueWords.slice(i, i + batchSize);

    const { data, error } = await supabase
      .from("global_words")
      .upsert(batch, { onConflict: "word" });

    if (error) {
      console.error(`❌ Batch error at index ${i}:`, error.message);
      // Continue with next batch instead of aborting
      continue;
    }

    const count = batch.length;
    inserted += count;

    const progress = Math.min(i + batchSize, uniqueWords.length);
    const pct = ((progress / uniqueWords.length) * 100).toFixed(1);
    console.log(`📦 Progress: ${progress}/${uniqueWords.length} (${pct}%) — last: "${batch[batch.length - 1].word}"`);
  }

  console.log(`\n🎉 Seed complete! Inserted/updated ${inserted} words in Supabase.`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
